# Generated by Django 4.2.26 on 2025-11-19 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField(blank=True, null=True, verbose_name='Temat spotkania')),
                ('status', models.CharField(choices=[('Pending', 'Oczekująca'), ('Confirmed', 'Potwierdzona'), ('Cancelled', 'Anulowana'), ('Completed', 'Zakończona'), ('No-Show Student', 'Nieobecność Studenta'), ('No-Show Lecturer', 'Nieobecność Prowadzącego')], default='Confirmed', max_length=20, verbose_name='Status rezerwacji')),
                ('booked_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia rezerwacji')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='schedules.availableslot', verbose_name='Zarezerwowany slot')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_reservations', to=settings.AUTH_USER_MODEL, verbose_name='Rezerwujący student')),
            ],
            options={
                'verbose_name': 'Rezerwacja',
                'verbose_name_plural': 'Rezerwacje',
                'ordering': ['slot__start_time'],
            },
        ),
    ]
