# Generated by Django 4.2.26 on 2025-11-17 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Tresc powiadomienia')),
                ('notification_type', models.CharField(choices=[('RESERVATION_CONFIRMATION', 'Potwierdzenie rezerwacji'), ('RESERVATION_CANCELLATION', 'Anulowanie rezerwacji'), ('SLOT_UPDATE', 'Aktualizacja terminu'), ('NEW_RESERVATION', 'Nowa rezerwacja')], default='NEW_RESERVATION', max_length=255, verbose_name='Typ powiadomienia')),
                ('is_seen', models.BooleanField(default=False, verbose_name='Czy odczytane?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Odbiorca')),
            ],
            options={
                'verbose_name': 'Powiadomienie',
                'verbose_name_plural': 'Powiadomienia',
                'ordering': ['-created_at'],
            },
        ),
    ]
