# Generated by Django 4.2.26 on 2025-11-13 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Początek slotu')),
                ('end_time', models.DateTimeField(verbose_name='Koniec slotu')),
                ('meeting_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Miejsce spotkania (np. Budynek B5, pokój 410)')),
                ('max_attendees', models.PositiveSmallIntegerField(default=1, verbose_name='Maksymalna liczba studentów na slot')),
                ('is_active', models.BooleanField(default=True, verbose_name='Czy slot jest aktywny/moze byc rezerwowany')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dostępny slot',
                'verbose_name_plural': 'Dostępne sloty',
                'ordering': ['start_time'],
            },
        ),
    ]
